version: "3"
services:
  node-docker:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MOUNGO_USERNAME=root
      - SESSION_SECRET=secret
      - MOUNGO_PASS=root
      - REDIS_PORT=6379
    command: npm run dev
  nginx: 
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports: 
      - 3000:80
