version: '3'
services: 
  nginx: 
    volumes: 
      - /nginx/default.conf:/usr/share/nginx/html
    ports: 
      - 80:80
  node-docker:
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment: 
      - PORT:3000
    command: npm run start