version: "3"
services:
  node-docker:
    build:
      context: .
      args:
        NODE_ENV: development

    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MOUNGO_USERNAME=root
      - MOUNGO_PASS=root
      - REDIS_PORT=6071
    command: npm run dev
