version: "3"
services:
  node-docker:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT:3000
    depends_on:
      - mongo
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - node-docker
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    image: redis

volumes:
  mongo-db:
