version: "3"
services:
  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
  node-docker:
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 15s
      restart_policy:
        condition: any
        delay: 10s
    build:
      context: .
      args:
        NODE_ENV: production
    image: jameskwan96/node-docker
    environment:
      - NODE_ENV=production
      - MOUNGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MOUNGO_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_PORT=6379
    command: npm run start
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
