version: '3'
services: 
  node-docker:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app
      - /app/node_modules
    environment: 
      - PORT:3000
    command: npm run dev